@startuml

skinparam shadowing false

class DAO << (J,red) >>
class DBConnector << (J,red) >>
class CupCake << (E,lightblue) >>
class CupCakePiece << (E,lightblue) >>
class Order << (E,lightblue) >>
class Orderline << (E,lightblue) >>
class User << (E,lightblue) >>

CupCake : - CupCakePiece bottom
CupCake : - CupCakePiece topping
CupCake : - double price
CupCake : - int amount
CupCake : + CupCake()
CupCake : + CupCakePiece getBottom()
CupCake : + CupCakePiece getTopping()
CupCake : + double getPrice()
CupCake : + int getAmount()
CupCake : + int hashCode()
CupCake : + boolean equals()
CupCake : + void addAmount()
CupCake : + void setAmount()
CupCake : + String toString()
CupCakePiece : - int id
CupCakePiece : - String flavor
CupCakePiece : - double price
CupCakePiece : + CupCakePiece()
CupCakePiece : + int getId()
CupCakePiece : + String getFlavor()
CupCakePiece : + double getPrice()
CupCakePiece : + String toString()
CupCakePiece : + int hashCode()
CupCakePiece : + boolean equals()
Order : - int id
Order : - ArrayList<Orderline> orderlines
Order : - double totalPrice
Order : - String dateTime
Order : + Order()
Order : - void setPrice()
Order : + int getId()
Order : + ArrayList<Orderlines> getOrderlines()
Order : + double getTotalPrice()
Order : + String getDateTime()
Orderline : - int userId
Orderline : - int orderId
Orderline : - int orderLineId
Orderline : - CupCake cupCake
Orderline : + OrderLine()
Orderline : + int getUserId()
Orderline : + int getOrderId()
Orderline : + int getOrderlineId()
Orderline : + CupCake getCupCake()
Orderline : + String toString()
Orderline : + int hashCode()
Orderline : + boolean equals()
User : - int id
User : - String username
User : - String password
User : - double balance
User : - String role
User : + User()
User : + String toString()
User : + int getId()
User : + String getUsername()
User : + String getPassword()
User : + double getBalance()
User : + String getRole()'
DAO : - DBConnector conn
DAO : + User getUser()
DAO : + User getUser()
DAO : + ArrayList<User> getUsers()
DAO : + boolean createCustomer()
DAO : + boolean createAdmin()
DAO : + ArrayList<CupCakePiece> getToppings()
DAO : + ArrayList<CupCakePiece> getBottoms()
DAO : + CupCakePiece getTopping()
DAO : + CupCakePiece getBottom()
DAO : + User login()
DAO : + Order getOrder()
DAO : + ArrayList<Order> getUsersOrders()
DAO : + ArrayList<Order> getAllOrders()
DAO : + int insertOrder()
DAO : + boolean addTopping()
DAO : + boolean addBottom()
DAO : + boolean changeOrderlineAmount()
DAO : + String getUserById()
DAO : + double deposit()
DAO : + boolean withdrawal()
DAO : + void updateOrderLine()
DBConnector : - Connection conn
DBConnector : - String IP
DBConnector : - int PORT
DBConnector : + String DATABASE
DBConnector : - String USERNAME
DBConnector : - String PASSWORD
DBConnector : + DBConnector()
DBConnector : + Connection getConnection()

CupCake "*" -left- "2" CupCakePiece
Order "1" -right- "*" Orderline
Orderline "*" -- "1" CupCake
User "1" -- "*" Order
User "1" -- "*" Orderline
DAO --> DBConnector

@enduml
