@startuml
skinparam backgroundColor wihte
skinparam Shadowing false

Title Logging in
State loginPage.jsp
State "Login Error" as error
State "ShopPage.jsp" as LoggedIn

note right of LoggedIn
User logged in
and stored in session
end note

[*] -> loginPage.jsp
loginPage.jsp --> LoggedIn : user and pw OK
loginPage.jsp --> error : user or pw not OK
error --> loginPage.jsp : try-again
LoggedIn --> [*]
@enduml