@startuml

title Navigations Diagram
skinparam TitleFontSize 40
skinparam shadowing false

[*] --> index.jsp
createUserPage.jsp --> welcomePage
header.jsp --> welcomePage
index.jsp --> welcomePage
loginPage.jsp --> welcomePage
welcomePage --> createUserPage.jsp
welcomePage --> loginPage.jsp
welcomePage --> shopPage

state loggedIn {
header.jsp --> logout.jsp
header.jsp --> usersPage
logout.jsp --> welcomePage
proOrderPage.jsp --> userSpecificOrderPage.jsp
shopPage --> index.jsp
shopPage --> shopPage.jsp
shopPage --> usersPage
shopPage.jsp --> shopPage
userOrderPage.jsp --> userSpecificOrderPage.jsp
usersPage --> index.jsp
usersPage --> proOrderPage.jsp
usersPage --> userOrderPage.jsp
userSpecificOrderPage.jsp --> proOrderPage.jsp
}

state admin {
adminOrderPage --> adminOrdersPage.jsp
adminOrderPage --> adminSpecificOrderPage.jsp
adminOrderPage --> index.jsp
adminOrdersPage.jsp --> adminSpecificOrderPage.jsp
adminOrdersPage.jsp --> createPiece
adminSpecificOrderPage.jsp --> adminOrdersPage.jsp
createPiece --> createPiece.jsp
header.jsp --> adminOrderPage
updateInvoice --> adminOrderPage
}

@enduml