@startuml

skinparam Shadowing false

title "Login - Sequence Diagram"

actor User
boundary loginPage.jsp as login
boundary shopPage.jsp as shop
participant shopPage as shopser
participant welcomePage as welcome
participant DAO
database Database

User -> login : username & password
login -> welcome: http POST login
welcome -> DAO: validate()
DAO -> Database: executeQuery()
Database -> DAO: resultset
DAO -> DAO: validate resultset
DAO -> welcome: OK
welcome -> shopser: redirect
shopser -> shop: forward
shop -> User: Welcome

@enduml